from .shutdown import Shutdown
from .signin import SigninResource
from .current_user import CurrentUserResource
from .signup import SignupResource
from .user_list import UserListResource
from .user import UserResource
from .admin_list import AdminListResource
from .friends_list import FriendsListResource
from .friends_requests import FriendsRequestsResource
from .add_friend import AddFriendResource